key_list = [
    'LEARNING_RATE',
    'DECAY',
    'STATE_DIM',
    'ACTION_DIM',
    'DENSE_LAYER_1_UNIT',
    'DENSE_LAYER_2_UNIT',
    'OUTPUT_LAYER',
]


# TODO
# CHANGE THE KEY LIST TO JSON DATA TYPE
